version: "3.7"

services:

  postgres:
    image: postgres:14.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ./database/postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - kpn-assignment

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    container_name: api
    command: run
    restart: always
    ports:
      - 5010:3001
      - 5678:5678
    env_file: ./backend/.env
    volumes:
      - ./backend:/api
    networks:
      - kpn-assignment


  ui:
    build:
      context: .
      dockerfile: docker/ui.Dockerfile
    container_name: kpn-ui
    restart: on-failure
    ports:
      - 3000:5173
    command: start
    env_file: ./frontend/.env
    environment:
      - NODE_ENV=local
      - NODE_PORT=3000
    volumes:
      - ./frontend:/app/mnt
      - ./frontend/node_modules:/app/mnt/node_modules
    networks:
      - kpn-assignment

networks:
  kpn-assignment:
    name: kpn-assignment
